### ISSUE TITLE
Disable the Webview2 security policy

### ISSUE THREAD

**Issue by jinpy666** [wailsapp/wails#1507]
### Is your feature request related to a problem? Please describe.

For some crawlers, multi-account management of web projects is very meaningful ~ hope to support. Thank you so much for your team's work.

### Describe the solution you'd like

CORS requests need to be supported.
Read and write cookies and storages of any site.

**Comment by misitebao** [comment]
You can follow this issue.

https://github.com/MicrosoftEdge/WebView2Feedback/issues/2558

**Comment by yildirimcagri** [comment]
Hi, you can use the [--disable-web-security](https://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome), browser flag (at your own risk since this disables security policies such as cross origin restrictions :) ) to achieve what you are looking for. We don't intend to provide an API for this at the moment due to security risks involved. Hope this helps!

**Comment by jinpy666** [comment]
Thank you~ @yildirimcagri @misitebao

**Comment by KiddoV** [comment]
This would answer my #1375 as well, but I am still not sure how do you put flag ``--disable-web-security`` in ``wails``?

**Comment by leaanthony** [comment]
Yeah, we could look at just adding a passthrough string to the options. I haven't really had a chance to consider the implications though

**Comment by Qendolin** [comment]
The CORS policy really is a pain since reading local files is a common use-case for desktop apps and 'proxying' them via the asset handler is not always feasible and presents a security risk if not properly implemented. I hope this issue is resolved soon.

**Comment by leaanthony** [comment]
It's scheduled. If you want to raise a PR sooner, feel free 👍

**Comment by fynxiu** [comment]
``` golang
  os.Setenv("WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS", "--disable-web-security")
```

**Comment by stffabi** [comment]
> ```go
>   os.Setenv("WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS", "--disable-web-security")
> ```

That won't work anymore since PR #1771 has been merged and will also not work with new native go-webview2loader (currently experimental) merged with PR #1974.

**Comment by stffabi** [comment]
Yeah supporting this is now pretty straight forward with the new go-webview2loader.

From a personal view I'm still not 100% sure if this should be supported right out of the box. Because that easily opens an app for several security problems if one doesn't take care what will be loaded into the frontend.

**Comment by haranobuhardo** [comment]
> It's scheduled. If you want to raise a PR sooner, feel free 👍

Hi @leaanthony , sorry for replying an old issue, but may I know what's the last status of this enhancement? I see someone opened a PR #2476 couple months ago, but haven't got finalized yet until now.

I really need this feature to use Wails any further, and I'm willing to help to create a PR if it is still "relevant" (since this feature should be included in 2.3 milestone, but somehow ignored).

**Comment by leaanthony** [comment]
Yeah, I think this is the wrong way to go about it. The correct way would be to use middleware to make the requests for you and ignore the TLS certificates in Go. That way it'll work on all platforms and we don't relax the webview security policy.

**Comment by haranobuhardo** [comment]
> Yeah, I think this is the wrong way to go about it. The correct way would be to use middleware to make the requests for you and ignore the TLS certificates in Go. That way it'll work on all platforms and we don't relax the webview security policy.

So, it's like creating a universal CORS middleware and keep the middleware running as long as the user need the feature to bypass the CORS. Correct?

**Comment by leaanthony** [comment]
It's not just about CORS but in general I'd choose to deal with remote resources in Go. You can lock it down better.

**Comment by imthatgin** [comment]
Is there a viable way to bypass X-Frame-Options in Wails today, for purely local apps?

**Comment by dzonerzy** [comment]
Sorry for commenting to an old Issue, I know this is not the way to go,  but for my specific use case my app spawn a Websocket server and I want to communicate over it , there's no need to say it won't connect since my Websocker server use a self-signed certificate, I already added the code to automatically insert the certificate into the root trust CA, but during dev mode I would love to have a way to disable the certificate check for the whole application, is there a way to achieve this?

**Comment by Dexus** [comment]
> Sorry for commenting to an old Issue, I know this is not the way to go, but for my specific use case my app spawn a Websocket server and I want to communicate over it , there's no need to say it won't connect since my Websocker server use a self-signed certificate, I already added the code to automatically insert the certificate into the root trust CA, but during dev mode I would love to have a way to disable the certificate check for the whole application, is there a way to achieve this?

`--ignore-certificate-errors` as flag should work

**Comment by dzonerzy** [comment]
How can I pass such parameters to the webview?

**Comment by iamkhalidbashir** [comment]
I am getting following error:
```
[Error] Unhandled Promise Rejection: CompileError: Refused to create a WebAssembly object because 'unsafe-eval' or 'wasm-unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src * 'u...
	(anonymous function) (App.tsx:55)
```

how to fix it?

**Comment by TaceyWong** [comment]
Anyone will fork a new branch of wails to resolve this requirement ？

It has been going on for 4 years and the wails maintainers have not decide to solved this.

**Comment by leaanthony** [comment]
It's been 2 years and we haven't chosen not to solve it, there are just more important things we need to do. It's a simple-ish change to pass through the flag but nobody seems excited enough to do it...

**Comment by leaanthony** [comment]
I've added `EnabledFeatures` and `DisabledFeatures` to the v3-alpha branch. Closing for now. Please feel free to reopen if you still want this looked at 👍

**Comment by 59de44955ebd** [comment]
I wanted to use [SharedArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer) in a WebView2-based desktop app that only loads local content (without server). It turned out to be quite tricky, but after testing all kind of workarrounds I finally found a solution and thought I'd share it here:
script [coi-serviceworker.js](https://github.com/gzuidhof/coi-serviceworker) works fine **if and only if** you use `SetVirtualHostNameToFolderMapping` to create a folder mapping for hostname `localhost` - i.e. overwrite the default meaning of "localhost" - and then serve your content from "http://localhost/" (not "https://" in this case).
