### ISSUE TITLE
[V2] Error on wails dev command 

### ISSUE THREAD

**Issue by stevohuncho** [wailsapp/wails#1680]
### Description

- I was receiving the error ```ERROR: io: read/write on closed pipe``` when executing the command ```wails dev```
At the time wails build would work perfectly fine, but for some reason the dev command was giving me this issue
That last night I wasn't having this issue so I had a friend download the repo to replicate the error, and they received the same exact one. I was wondering if I would be able to reproduce this on older wails projects of mine, and on a project that worked fine and I haven't touched in weeks gave me the same error.

### To Reproduce

Wails V2 CLI beta-42
React TS Template Project
```wails dev```

### Expected behaviour

My project to be hosted in a development environment where I can edit it live.

### Screenshots

![image](https://user-images.githubusercontent.com/93010314/182028026-a2bc0e8d-7c3f-43ad-8655-730420bf3353.png)

### Attempted Fixes

- I thought it was because of my wails cli version and when switching to a version below beta 40 (I use v39 now) the ```wails dev``` command worked perfectly fine again.

### System Details

```shell
System
------
OS:             Windows 10 Home
Version:        2009 (Build: 19044)
ID:             21H2
Go Version:     go1.18.3
Platform:       windows
Architecture:   amd64

Wails
------
Version:        v2.0.0-beta.42

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       103.0.1264.77
npm             N/A             Installed       8.15.0
*upx            N/A             Available
*nsis           N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
```

**Comment by leaanthony** [comment]
Thanks for reporting this. Let's investigate

**Comment by leaanthony** [comment]
If you have time, is there any chance you could `git bisect` this? Thanks 🙏

**Comment by akhudek** [comment]
I just switched from <40 to version 42 and am also getting issues with `wails dev`. In my case I most frequently get:

```
failed to load config from projectdir/frontend/vite.config.ts
error when starting dev server:
Error: ENOENT: no such file or directory, unlink 'projectdir/frontend/vite.config.ts.js'
```

Though curiously when I enable increased verbosity it sometimes passes this stage (though usually not). It looks like a timing issue of some sort to me. Running `npm run build` in `frontend` manually works every time.

**Comment by akhudek** [comment]
Ok, the issue @stevohuncho encountered is because wails now runs `npm install` in `frontend` and it's throwing an error, but the wails frontend isn't showing the error. 

I think the problem that I'm running into is that wails runs `npm run dev` *before* running `npm build`. Is there a reason for this? Why do we run both commands anyways? But it certainly seems that build should be run and *then* `npm run dev` if both are needed.

I upgraded to vite 3 and the issue with the dev server seems to be fixed FWIW.

**Comment by akhudek** [comment]
Confirmed that running build before starting the dev server fixes my problems. Small aside, vite changed the default port it runs on, it might be worth updating the starter template to specify a fixed dev port to prevent future upgrade issues for people.

**Comment by leaanthony** [comment]
Hi! 👋 I believe these issues are fixed on master 👍

**Comment by akhudek** [comment]
Doesn't look like it. This block https://github.com/wailsapp/wails/blob/master/v2/cmd/wails/internal/commands/dev/dev.go#L209 should be moved to after the frontend build https://github.com/wailsapp/wails/blob/master/v2/cmd/wails/internal/commands/dev/dev.go#L222. Otherwise you get strange race conditions and the dev watcher can intermittently fail.

**Comment by leaanthony** [comment]
Thanks for confirming. There was a commit last night that may have affected this. Will check today 👍

**Comment by stffabi** [comment]
The easiest would probably be to internally add a buildOption to only build the frontend. Then replace the following code-block with a call to just build the frontend `_, err := build.Build(buildOptionsFrontendOnly)`

https://github.com/wailsapp/wails/blob/b33211495ef8acd0a4637b283f947d3d0fe64e55/v2/cmd/wails/internal/commands/dev/dev.go#L189-L206

This should fix the problem of discarded output from `frontend:dev:install` and also makes sure to build the frontend once before starting the `frontend:dev:watcher`.

**Comment by leaanthony** [comment]
There was a scenario where Dev wouldn't work on a new system because Vite wasn't installed so we need to install frontend dependencies before running Dev. However, this was running the Dev command and not the build command. This was fixed recently, but it sounds like you're still seeing it run build and not install?

**Comment by akhudek** [comment]
When you do `wails dev` it currently does, in order: `npm install`, `npm run dev`, `npm run build`. The issue I'm facing is that running build after running dev causes conflicts and the dev watcher dies.

**Comment by akhudek** [comment]
The original issue is different though, it's that `wails dev` wasn't surfacing errors in `npm install` and instead just giving a broken pipe error. So there are two issues at play.

**Comment by leaanthony** [comment]
Thanks for taking the time to diagnose these issues. I really appreciate it 🙏

**Comment by stffabi** [comment]
I've created the draft PR #1694, which should fix these issues. 

@akhudek  and @stevohuncho would it be possible for you to try out the PR? That would be awesome 🙏

**Comment by stffabi** [comment]
@akhudek thanks for testing 🙏 . The PR has been merged and should also fix the issue @stevohuncho reported.

I'm going to close this issue. Please feel free to reopen if you see any further problems.
