### ISSUE TITLE
[v3] SetProcessDpiAwarenessContext failed 0: 18446744073709551612 Access is denied.

### ISSUE THREAD

**Issue by alessandro-ooo** [wailsapp/wails#4803]
### Description

When you run `wails3 dev`, in the spam of logs you can notice this error popping up. The application works just fine though, no crash or errors. It seems to happen at the same time the frontend is online.

### To Reproduce

1. run `wails3 dev`
2. check terminal
3. you should see something like this:

`  VITE v7.3.0  ready in 212 ms

  ➜  Local:   http://localhost:9245/
  ➜  Network: use --host to expose
Dec 15 19:31:34.030 INF Connected to frontend dev server!
Dec 15 19:31:34.030 ERR SetProcessDpiAwarenessContext failed 0: 18446744073709551612 Access is denied.`

### Expected behaviour

I believe the application shouldn't be starting? unless it's something that doesn't have a big impact on it.

### Screenshots

<img width="960" height="207" alt="Image" src="https://github.com/user-attachments/assets/9c64afea-4dd0-444d-b81f-003fe95d0603" />

### Attempted Fixes

I've tried in a new and fresh project as well (without editing the frontend) but ain't fixed.

### System Details

```shell
Wails Doctor          
                                


# Wails
Version | v2.10.2


# System
┌────────────────────────────────────────────────────────────────────────┐
| OS           | Windows 10 Home                                         |
| Version      | 2009 (Build: 26100)                                     |
| ID           | 24H2                                                    |
| Branding     | Windows 11 Home                                         |
| Go Version   | go1.25.1                                                |
| Platform     | windows                                                 |
| Architecture | amd64                                                   |
| CPU          | AMD Ryzen 5 5600X 6-Core Processor                      |
| GPU          | NVIDIA GeForce RTX 3060 (NVIDIA) - Driver: 32.0.15.8157 |
| Memory       | 32GB                                                    |
└────────────────────────────────────────────────────────────────────────┘

# Dependencies
┌───────────────────────────────────────────────────────┐
| Dependency | Package Name | Status    | Version       |
| WebView2   | N/A          | Installed | 143.0.3650.80 |
| Nodejs     | N/A          | Installed | 24.9.0        |
| npm        | N/A          | Installed | 10.5.0        |
| *upx       | N/A          | Available |               |
| *nsis      | N/A          | Available |               |
|                                                       |
└─────────────── * - Optional Dependency ───────────────┘

# Diagnosis
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/
```

**Comment by lonepawdev** [comment]
I stumbled upon this myself when looking at why my iconify icons looked a little blurry, trying to get some nice custom min, max, restore and close icons for a custom titlebar with windows controls, but I think thats an svg size/scaling/viewport issue which is bugging me.

Digging into this error message I found the issue I think. So windows documentation states you have 2 methods of setting dpi awareness:

1. Through an application manifest setting
2. Programmatically through an API call

Using the application manifest is the recommended option, rarther than the api call. What i belive it doesn't mention in the docs is that you can't do both, and it looks like the manifest setting is therfore applied long before the call to the api from wails.

[Setting the default DPI awareness for a process](https://learn.microsoft.com/en-us/windows/win32/hidpi/setting-the-default-dpi-awareness-for-a-process)

And looking through api docs [SetProcessDpiAwarenessContext function (winuser.h)](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setprocessdpiawarenesscontext) we have a few remarks: 

`You must call this API before you call any APIs that depend on the DPI awareness (including before creating any UI in your process). Once API awareness is set for an app, any future calls to this API will fail. This is true regardless of whether you set the DPI awareness in the manifest or by using this API.

If the DPI awareness level is not set, the default value is DPI_AWARENESS_CONTEXT_UNAWARE.`

So thats why the error is occurring because its in the manifest you cannot use the api calls. Its probably best to just use manifest then as the api is not recommended or leave api stuff in and could give user a choice to remove the dpi stuff from manifest.

However I did notice during testing that didnt matter whether I set true/pm and PerMonitorV2, PerMonitor neither change was present in the final exe when checking the manifest inside. This is due to the winres library at [manifest.go#L209](https://github.com/tc-hib/winres/blob/master/manifest.go#L209) the switch here and when setting true/pm and PerMonitorV2, PerMonitor it will just select the DPIPerMonitorV2 case:

```go
case DPIPerMonitorV2:
		// PerMonitorV2 fixes the scale on secondary monitors
		// If not available, the closest option seems to be System
		vars.DPIAware = "true"
		vars.DPIAwareness = "permonitorv2,system"
```

Editing the manifest with external tools i was able to set dpi to correct value obviously still resulting in error, and removing dpi awareness from manifest does stop error because api can now call it without issue, wether its called early enough ive not checked but, this is why the error happens.

**Comment by leaanthony** [comment]
The linked PR should fix this if anyone is willing to try it out 👍

**Comment by alessandro-ooo** [comment]
Will test as soon as I get home

**Comment by alessandro-ooo** [comment]
@leaanthony I'm trying to test this pr but it seems like I can't install it, I get an error when I run `go install`, that's my logs:

``` *  History restored 
PS C:\Users\Alessandro\Desktop\prtest> git clone https://github.com/wailsapp/wails
Cloning into 'wails'...
remote: Enumerating objects: 79416, done.
remote: Counting objects: 100% (1331/1331), done.
remote: Compressing objects: 100% (627/627), done.
remote: Total 79416 (delta 1044), reused 712 (delta 704), pack-reused 78085 (from 4)
Receiving objects: 100% (79416/79416), 270.07 MiB | 3.20 MiB/s, done.
Resolving deltas: 100% (53727/53727), done.
Updating files: 100% (6578/6578), done.
PS C:\Users\Alessandro\Desktop\prtest> cd wails
PS C:\Users\Alessandro\Desktop\prtest\wails> git fetch -u origin pull/4811/head:test/pr-4811
From https://github.com/wailsapp/wails
 * [new ref]             refs/pull/4811/head -> test/pr-4811
PS C:\Users\Alessandro\Desktop\prtest\wails> git checkout test/pr-4811
Updating files: 100% (5020/5020), done.
Switched to branch 'test/pr-4811'
PS C:\Users\Alessandro\Desktop\prtest\wails> git reset --hard HEAD
HEAD is now at 9d8216461 fix(windows): skip DPI awareness API call when already set via manifest
PS C:\Users\Alessandro\Desktop\prtest\wails> cd v2/cmd/wails
PS C:\Users\Alessandro\Desktop\prtest\wails\v2\cmd\wails> go install
# golang.org/x/tools/internal/tokeninternal
..\..\..\..\..\..\go\pkg\mod\golang.org\x\tools@v0.17.0\internal\tokeninternal\tokeninternal.go:78:9: invalid array length -delta * delta (constant -256 of type int64) 
PS C:\Users\Alessandro\Desktop\prtest\wails\v2\cmd\wails>

```

I've followed [THIS GUIDE ](https://wails.io/docs/guides/local-development/#testing-a-pr)

**Comment by lonepawdev** [comment]
@alessandro-ooo The branch is **vk/e67e-setdpi-issue**, or you can use the github cli and do:

```
gh pr checkout 4811
```

tl;dr It works if no manifest changes made, winres doesn't correctly make manifest in exe with users dpi settings exactly and always adds even if excluded.

---

In regards to the pr this does stop the error if you make no changes to the manifest in build, in testing removing dpi stuff from manifest in build causes winres to still add the dpi sections setting them to unaware which still seems to conflict with setting dpi programmatically. 

Removing the dpi sections in the exe manifest after build causes no error. In [application manifest](https://learn.microsoft.com/en-us/windows/win32/sbscs/application-manifests) it says:

`Absent	: The current process is dpi unaware by default. You can programmatically change this setting by calling the SetProcessDpiAwareness or SetProcessDPIAware function.`

`Contains any other string: 	Windows Vista, Windows 7 and Windows 8: The behavior is the same as when the dpiAware is absent.
Windows 8.1 and Windows 10: The current process is dpi unaware, and you cannot programmatically change this setting by calling the SetProcessDpiAwareness or SetProcessDPIAware function.`

Because winres always adds we cannot set it via api. Maybe switching to another library for embedding resources might be needed [goversioninfo](https://github.com/josephspurrier/goversioninfo) might be suitable, but maybe this is for another issue.

**Comment by alessandro-ooo** [comment]
@lonepawdev sorry I didn't have time to test the pr again today, will prolly try tomorrow unless you've tested it already and it's not fixed?

**Comment by WCY-dt** [comment]
I can confirm I'm experiencing the same issue with my Wails v3 application.

**Environment:**

- OS: Windows 11
- Wails CLI: v3.0.0-alpha.48
- Go Version: go version go1.24.2 windows/amd64

**Error Message:**

```
SetProcessDpiAwarenessContext failed 0: 18446744073709551612 Access is denied.
```

**Observations:**

- The error appears consistently during `wails3 dev`
- The application runs normally without any functional issues
- UI rendering and DPI scaling work as expected
- Occurs even when running with administrator privileges

**Impact:** 

None - this is just a warning message in the logs. The application functions perfectly otherwise.

**Comment by alessandro-ooo** [comment]
> I can confirm I'm experiencing the same issue with my Wails v3 application.
> 
> **Environment:**
> 
> * OS: Windows 11
> * Wails CLI: v3.0.0-alpha.48
> * Go Version: go version go1.24.2 windows/amd64
> 
> **Error Message:**
> 
> ```
> SetProcessDpiAwarenessContext failed 0: 18446744073709551612 Access is denied.
> ```
> 
> **Observations:**
> 
> * The error appears consistently during `wails3 dev`
> * The application runs normally without any functional issues
> * UI rendering and DPI scaling work as expected
> * Occurs even when running with administrator privileges
> 
> **Impact:**
> 
> None - this is just a warning message in the logs. The application functions perfectly otherwise.

Did you try the pr?

**Comment by qsdebug** [comment]
> The linked PR should fix this if anyone is willing to try it out 👍如果有人愿意尝试👍，链接的 PR 应该能解决这个问题

i try it, the issue has been completely resolved. it needs to be merged as soon as possible

`
Jan 20 09:01:35.390 INF Retrying...
Jan 20 09:01:35.412 INF Connected to frontend dev server!
Jan 20 09:01:35.412 ERR SetProcessDpiAwarenessContext failed 0: 18446744073709551612 Access is denied.
2026/01/20 09:01:35 [WebView2] Environment created successfully

----------------------
Jan 20 09:01:52.200 INF Retrying...
Jan 20 09:01:52.220 INF Connected to frontend dev server!
2026/01/20 09:01:52 [WebView2] Environment created successfully
`

**Comment by leaanthony** [comment]
Merged!
