### ISSUE TITLE
v2 windows build fails due to gcc missing

### ISSUE THREAD

**Issue by kjk** [wailsapp/wails#832]
**Description**

A build of sample v2 app on windows fails with:
```
# github.com/wailsapp/wails/v2/internal/frontend/desktop/windows
cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in %PATH%
```

**To Reproduce**
Steps to reproduce the behaviour:
1. I have `go version go1.17.1 windows/amd64` installed with chocolatey
2. used `wails init -m test`
3. `cd test`
4. `wails dev`

I get the above error. There is no gcc.exe shipped with my Go install.

Maybe it's because Go is installed with chocolatey.

Here's the output of `wails doctor`:
```
PS C:\> wails doctor
Wails CLI v2.0.0-beta.1


Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Pro
Version:        2009 (Build: 22000)
ID:             21H2
Go Version:     go1.17.1
Platform:       windows
Architecture:   amd64

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       94.0.992.31
npm             N/A             Installed       7.20.5
*upx            N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
```

**Comment by leaanthony** [comment]
Hi there. gcc is absolutely not needed for Wails so this sounds like a Go installation error. Can you please try installing using the official installer?

**Comment by kjk** [comment]
In `wailsapp/wails/v2/internal/frontend/desktop/windows/dialog.go`:
```
import "C"
```

`import "C"` triggers cgo which requires `gcc`.

It doesn't look like the `C` is used anywhere.

**Comment by kjk** [comment]
See https://github.com/golang/go/wiki/cgo#windows
> In order to use cgo on Windows, you'll also need to first install a gcc compiler (for instance, mingw-w64) and have gcc.exe (etc.) in your PATH environment variable before compiling with cgo will work.

**Comment by leaanthony** [comment]
That's so weird! Firstly, why is there no compile error? Secondly, how did it get there? and finally: How is this not an error on my machine 👀 I'll push a fix right away. Thanks for investigating!

**Comment by leaanthony** [comment]
I've pushed the fixes on master. Please test and let me know if that fixes it. I imagine I'll get beta.2 out shortly, maybe tomorrow

**Comment by kjk** [comment]
Don't know how to force using master.

I tried `go install github.com/wailsapp/wails/v2/cmd/wails@master` which seems to build wails from master but `wails build` still identifies itself as `v2.0.0-beta.1` and has the same issue probably because it downloads `v2.0.0-beta.1` tag.

So I think you would have to push new tag or describe how to force wails to use master branch.

**Comment by leaanthony** [comment]
Just pushed `v2.0.0-beta.2`. Looks like the Go mod cache hasn't updated yet so give it an hour or so (This is a super annoying 'feature' of `go get` on releases that don't exist yet). Upgrade using `wails update -pre`.

**Comment by kjk** [comment]
The problem persists, see the log below.

Notice that CLI is beta2 but `wails biuld` still downloads beta1 code.

I did `go clean -modcache` and `$Env:GOPROXY="direct"` to disable Go module proxy.

Could it be because wailsapp/wails/v2/cmd/wails/internal/commands/generate/template/base/go.mod.tmpl still refers to `v2.0.0-beta.1` ?


```
> wails build -v 2
Wails CLI v2.0.0-beta.2



App Type:               desktop
Platform:               windows
Arch:                   amd64
Compiler:               C:\Program Files\Go\bin\go.exe
Skip Frontend:          false
Compress:               false
Package:                true
Clean Build Dir:        false
LDFlags:                ""
Tags:                   []

No Install command. Skipping.
No Build command. Skipping.
Generating bundle assets: Done.
Compiling application:
go: downloading github.com/wailsapp/wails/v2 v2.0.0-beta.1
```

**Comment by leaanthony** [comment]
Hey, just check that your project isn't referencing `beta.1` instead of `beta.2`. I'll add some code to auto migrate the version to your current cli version at some point.

**Comment by kjk** [comment]
great success! I can confirm I can build the template app.

You're right, it was stale reference to beta.1 in my go.mod

**Comment by leaanthony** [comment]
Hey thanks for bringing this up - you've uncovered a bug that was indirectly related to this: the templates have hard-coded versions 🤦 Thanks!
